"""initial_schema

Revision ID: 3705dca45203
Revises: 001
Create Date: 2026-03-28 22:32:19.412946

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3705dca45203'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('campaign_id', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('effective_status', sa.String(length=50), nullable=False),
    sa.Column('configured_status', sa.String(length=50), nullable=True),
    sa.Column('buying_type', sa.String(length=50), nullable=True),
    sa.Column('bid_strategy', sa.String(length=100), nullable=True),
    sa.Column('daily_budget', sa.BigInteger(), nullable=True),
    sa.Column('lifetime_budget', sa.BigInteger(), nullable=True),
    sa.Column('budget_remaining', sa.BigInteger(), nullable=True),
    sa.Column('spend_cap', sa.BigInteger(), nullable=True),
    sa.Column('is_budget_schedule_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_adset_budget_sharing_enabled', sa.Boolean(), nullable=True),
    sa.Column('special_ad_category', sa.String(length=100), nullable=True),
    sa.Column('pacing_type', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stop_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ad_accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_index(op.f('ix_campaigns_account_id'), 'campaigns', ['account_id'], unique=False)
    op.create_table('creatives',
    sa.Column('creative_id', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('call_to_action_type', sa.String(length=100), nullable=True),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('effective_instagram_media_id', sa.String(length=50), nullable=True),
    sa.Column('effective_object_story_id', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('video_id', sa.String(length=50), nullable=True),
    sa.Column('object_story_spec', sa.JSON(), nullable=True),
    sa.Column('asset_feed_spec', sa.JSON(), nullable=True),
    sa.Column('meta_created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ad_accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('creative_id')
    )
    op.create_index(op.f('ix_creatives_account_id'), 'creatives', ['account_id'], unique=False)
    op.create_table('sync_jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('chunk_size_days', sa.Integer(), nullable=False),
    sa.Column('cursor_date', sa.Date(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('days_processed', sa.Integer(), nullable=False),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('retry_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ad_accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_sync_jobs_account_id'), 'sync_jobs', ['account_id'], unique=False)
    op.create_table('ad_sets',
    sa.Column('adset_id', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('effective_status', sa.String(length=50), nullable=False),
    sa.Column('configured_status', sa.String(length=50), nullable=True),
    sa.Column('automatic_manual_state', sa.String(length=50), nullable=True),
    sa.Column('billing_event', sa.String(length=100), nullable=True),
    sa.Column('optimization_goal', sa.String(length=100), nullable=True),
    sa.Column('destination_type', sa.String(length=50), nullable=True),
    sa.Column('campaign_attribution', sa.String(length=50), nullable=True),
    sa.Column('campaign_active_time', sa.String(length=50), nullable=True),
    sa.Column('bid_strategy', sa.String(length=100), nullable=True),
    sa.Column('bid_amount', sa.BigInteger(), nullable=True),
    sa.Column('daily_budget', sa.BigInteger(), nullable=True),
    sa.Column('lifetime_budget', sa.BigInteger(), nullable=True),
    sa.Column('lifetime_imps', sa.BigInteger(), nullable=True),
    sa.Column('budget_remaining', sa.BigInteger(), nullable=True),
    sa.Column('daily_min_spend_target', sa.BigInteger(), nullable=True),
    sa.Column('daily_spend_cap', sa.BigInteger(), nullable=True),
    sa.Column('targeting', sa.JSON(), nullable=True),
    sa.Column('is_dynamic_creative', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ad_accounts.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('adset_id')
    )
    op.create_index(op.f('ix_ad_sets_account_id'), 'ad_sets', ['account_id'], unique=False)
    op.create_index(op.f('ix_ad_sets_campaign_id'), 'ad_sets', ['campaign_id'], unique=False)
    op.create_table('campaign_insights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_stop', sa.Date(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('reach', sa.BigInteger(), nullable=False),
    sa.Column('frequency', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cpm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cpp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inline_link_clicks', sa.BigInteger(), nullable=True),
    sa.Column('inline_link_click_ctr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('inline_post_engagement', sa.BigInteger(), nullable=True),
    sa.Column('social_spend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('cost_per_action_type', sa.JSON(), nullable=True),
    sa.Column('video_play_actions', sa.JSON(), nullable=True),
    sa.Column('video_p25_watched_actions', sa.JSON(), nullable=True),
    sa.Column('video_p50_watched_actions', sa.JSON(), nullable=True),
    sa.Column('video_p75_watched_actions', sa.JSON(), nullable=True),
    sa.Column('video_p95_watched_actions', sa.JSON(), nullable=True),
    sa.Column('video_p100_watched_actions', sa.JSON(), nullable=True),
    sa.Column('video_avg_time_watched_actions', sa.JSON(), nullable=True),
    sa.Column('outbound_clicks', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('cost_per_result', sa.JSON(), nullable=True),
    sa.Column('quality_ranking', sa.String(length=50), nullable=True),
    sa.Column('engagement_rate_ranking', sa.String(length=50), nullable=True),
    sa.Column('conversion_rate_ranking', sa.String(length=50), nullable=True),
    sa.Column('objective', sa.String(length=100), nullable=True),
    sa.Column('buying_type', sa.String(length=50), nullable=True),
    sa.Column('attribution_setting', sa.String(length=100), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'date_start', 'date_stop', name='uq_campaign_insight_date')
    )
    op.create_index(op.f('ix_campaign_insights_account_id'), 'campaign_insights', ['account_id'], unique=False)
    op.create_index(op.f('ix_campaign_insights_campaign_id'), 'campaign_insights', ['campaign_id'], unique=False)
    op.create_table('ads',
    sa.Column('ad_id', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=False),
    sa.Column('adset_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('effective_status', sa.String(length=50), nullable=False),
    sa.Column('configured_status', sa.String(length=50), nullable=True),
    sa.Column('creative_id', sa.String(length=50), nullable=True),
    sa.Column('engagement_audience', sa.Boolean(), nullable=True),
    sa.Column('ad_active_time', sa.String(length=50), nullable=True),
    sa.Column('bid_amount', sa.BigInteger(), nullable=True),
    sa.Column('conversion_domain', sa.String(length=255), nullable=True),
    sa.Column('display_sequence', sa.Integer(), nullable=True),
    sa.Column('ad_schedule_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ad_schedule_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ad_accounts.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['adset_id'], ['ad_sets.adset_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ad_id')
    )
    op.create_index(op.f('ix_ads_account_id'), 'ads', ['account_id'], unique=False)
    op.create_index(op.f('ix_ads_adset_id'), 'ads', ['adset_id'], unique=False)
    op.create_index(op.f('ix_ads_campaign_id'), 'ads', ['campaign_id'], unique=False)
    op.create_table('adset_insights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=False),
    sa.Column('adset_id', sa.String(length=50), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_stop', sa.Date(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('reach', sa.BigInteger(), nullable=False),
    sa.Column('frequency', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cpm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cpp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inline_link_clicks', sa.BigInteger(), nullable=True),
    sa.Column('inline_link_click_ctr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('inline_post_engagement', sa.BigInteger(), nullable=True),
    sa.Column('social_spend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('full_view_impressions', sa.BigInteger(), nullable=True),
    sa.Column('full_view_reach', sa.BigInteger(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('cost_per_action_type', sa.JSON(), nullable=True),
    sa.Column('video_play_actions', sa.JSON(), nullable=True),
    sa.Column('video_p25_watched_actions', sa.JSON(), nullable=True),
    sa.Column('video_p50_watched_actions', sa.JSON(), nullable=True),
    sa.Column('video_p75_watched_actions', sa.JSON(), nullable=True),
    sa.Column('video_p95_watched_actions', sa.JSON(), nullable=True),
    sa.Column('video_p100_watched_actions', sa.JSON(), nullable=True),
    sa.Column('video_avg_time_watched_actions', sa.JSON(), nullable=True),
    sa.Column('outbound_clicks', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('cost_per_result', sa.JSON(), nullable=True),
    sa.Column('quality_ranking', sa.String(length=50), nullable=True),
    sa.Column('engagement_rate_ranking', sa.String(length=50), nullable=True),
    sa.Column('conversion_rate_ranking', sa.String(length=50), nullable=True),
    sa.Column('objective', sa.String(length=100), nullable=True),
    sa.Column('buying_type', sa.String(length=50), nullable=True),
    sa.Column('attribution_setting', sa.String(length=100), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['adset_id'], ['ad_sets.adset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adset_id', 'date_start', 'date_stop', name='uq_adset_insight_date')
    )
    op.create_index(op.f('ix_adset_insights_account_id'), 'adset_insights', ['account_id'], unique=False)
    op.create_index(op.f('ix_adset_insights_adset_id'), 'adset_insights', ['adset_id'], unique=False)
    op.create_index(op.f('ix_adset_insights_campaign_id'), 'adset_insights', ['campaign_id'], unique=False)
    op.create_table('ad_insights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=False),
    sa.Column('adset_id', sa.String(length=50), nullable=False),
    sa.Column('ad_id', sa.String(length=50), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_stop', sa.Date(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('reach', sa.BigInteger(), nullable=False),
    sa.Column('frequency', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cpm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cpp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inline_link_clicks', sa.BigInteger(), nullable=True),
    sa.Column('inline_link_click_ctr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('inline_post_engagement', sa.BigInteger(), nullable=True),
    sa.Column('social_spend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_per_unique_click', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_per_outbound_click', sa.JSON(), nullable=True),
    sa.Column('cost_per_unique_outbound_click', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('cost_per_action_type', sa.JSON(), nullable=True),
    sa.Column('video_play_actions', sa.JSON(), nullable=True),
    sa.Column('video_p25_watched_actions', sa.JSON(), nullable=True),
    sa.Column('video_p50_watched_actions', sa.JSON(), nullable=True),
    sa.Column('video_p75_watched_actions', sa.JSON(), nullable=True),
    sa.Column('video_p95_watched_actions', sa.JSON(), nullable=True),
    sa.Column('video_p100_watched_actions', sa.JSON(), nullable=True),
    sa.Column('video_avg_time_watched_actions', sa.JSON(), nullable=True),
    sa.Column('outbound_clicks', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('cost_per_result', sa.JSON(), nullable=True),
    sa.Column('quality_ranking', sa.String(length=50), nullable=True),
    sa.Column('engagement_rate_ranking', sa.String(length=50), nullable=True),
    sa.Column('conversion_rate_ranking', sa.String(length=50), nullable=True),
    sa.Column('objective', sa.String(length=100), nullable=True),
    sa.Column('buying_type', sa.String(length=50), nullable=True),
    sa.Column('attribution_setting', sa.String(length=100), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.ad_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_id', 'date_start', 'date_stop', name='uq_ad_insight_date')
    )
    op.create_index(op.f('ix_ad_insights_account_id'), 'ad_insights', ['account_id'], unique=False)
    op.create_index(op.f('ix_ad_insights_ad_id'), 'ad_insights', ['ad_id'], unique=False)
    op.create_index(op.f('ix_ad_insights_adset_id'), 'ad_insights', ['adset_id'], unique=False)
    op.create_index(op.f('ix_ad_insights_campaign_id'), 'ad_insights', ['campaign_id'], unique=False)
    op.alter_column('ad_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ad_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ad_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ad_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ad_insights_campaign_id'), table_name='ad_insights')
    op.drop_index(op.f('ix_ad_insights_adset_id'), table_name='ad_insights')
    op.drop_index(op.f('ix_ad_insights_ad_id'), table_name='ad_insights')
    op.drop_index(op.f('ix_ad_insights_account_id'), table_name='ad_insights')
    op.drop_table('ad_insights')
    op.drop_index(op.f('ix_adset_insights_campaign_id'), table_name='adset_insights')
    op.drop_index(op.f('ix_adset_insights_adset_id'), table_name='adset_insights')
    op.drop_index(op.f('ix_adset_insights_account_id'), table_name='adset_insights')
    op.drop_table('adset_insights')
    op.drop_index(op.f('ix_ads_campaign_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_adset_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_account_id'), table_name='ads')
    op.drop_table('ads')
    op.drop_index(op.f('ix_campaign_insights_campaign_id'), table_name='campaign_insights')
    op.drop_index(op.f('ix_campaign_insights_account_id'), table_name='campaign_insights')
    op.drop_table('campaign_insights')
    op.drop_index(op.f('ix_ad_sets_campaign_id'), table_name='ad_sets')
    op.drop_index(op.f('ix_ad_sets_account_id'), table_name='ad_sets')
    op.drop_table('ad_sets')
    op.drop_index(op.f('ix_sync_jobs_account_id'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_index(op.f('ix_creatives_account_id'), table_name='creatives')
    op.drop_table('creatives')
    op.drop_index(op.f('ix_campaigns_account_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
